CREATE OR REPLACE DATABASE PROJECT_10;

CREATE OR REPLACE SCHEMA PROJECT_10.SCD;

USE DATABASE PROJECT_10;

USE SCHEMA SCD;


-- TASK 2: CREATE TYPE 3 DIMENSION

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3
(
    CUSTOMER_KEY        NUMBER AUTOINCREMENT,
    CUSTOMER_ID         NUMBER,
    CUSTOMER_NAME       VARCHAR(100),
    CITY                VARCHAR(100),
    STATE               VARCHAR(100),
    CURRENT_MEMBERSHIP  VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    SEGMENT             VARCHAR(50)
);

DESC TABLE DIM_CUSTOMER_TYPE3;

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE CUSTOMER_STAGE FILE_FORMAT = CUSTOMER_CSV_FORMAT;

LIST @CUSTOMER_STAGE;

INSERT INTO DIM_CUSTOMER_TYPE3
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
)
SELECT
    $1 AS CUSTOMER_ID,
    $2 AS CUSTOMER_NAME,
    $3 AS CITY,
    $4 AS STATE,
    $5 AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    $6 AS SEGMENT
FROM @CUSTOMER_STAGE/customers_initial.csv;

SELECT * FROM DIM_CUSTOMER_TYPE3;

LIST @CUSTOMER_STAGE;

SELECT
    $1 AS CUSTOMER_ID,
    $2 AS CUSTOMER_NAME,
    $3 AS CITY,
    $4 AS STATE,
    $5 AS MEMBERSHIP,
    $6 AS SEGMENT,
    $7 AS EFFECTIVE_DATE
FROM @CUSTOMER_STAGE/customer_updates.csv;

UPDATE DIM_CUSTOMER_TYPE3 AS T
SET
    PREVIOUS_MEMBERSHIP = T.CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP  = U.MEMBERSHIP,
    CITY                = U.CITY,
    STATE               = U.STATE,
    SEGMENT             = U.SEGMENT
FROM
(
    SELECT
        $1 AS CUSTOMER_ID,
        $2 AS CUSTOMER_NAME,
        $3 AS CITY,
        $4 AS STATE,
        $5 AS MEMBERSHIP,
        $6 AS SEGMENT,
        $7 AS EFFECTIVE_DATE
    FROM @CUSTOMER_STAGE/customer_updates.csv
) AS U
WHERE T.CUSTOMER_ID = U.CUSTOMER_ID;

SELECT * FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

SELECT * FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6
(
    CUSTOMER_KEY        NUMBER AUTOINCREMENT,
    CUSTOMER_ID         NUMBER,
    CUSTOMER_NAME       VARCHAR(100),
    CITY                VARCHAR(100),
    STATE               VARCHAR(100),
    CURRENT_MEMBERSHIP  VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),
    SEGMENT              VARCHAR(50),
    EFFECTIVE_DATE      DATE,
    EXPIRY_DATE         DATE,
    IS_CURRENT           BOOLEAN
);

DESC TABLE DIM_CUSTOMER_TYPE6;

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    $1 AS CUSTOMER_ID,
    $2 AS CUSTOMER_NAME,
    $3 AS CITY,
    $4 AS STATE,
    $5 AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    $5 AS HISTORICAL_MEMBERSHIP,
    $6 AS SEGMENT,
    '2026-01-01' AS EFFECTIVE_DATE,
    '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM @CUSTOMER_STAGE/customers_initial.csv;

SELECT * FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE6;

UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;

SELECT * FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101;

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    $1 AS CUSTOMER_ID,
    $2 AS CUSTOMER_NAME,
    $3 AS CITY,
    $4 AS STATE,
    $5 AS CURRENT_MEMBERSHIP,
    'Silver' AS PREVIOUS_MEMBERSHIP,
    $5 AS HISTORICAL_MEMBERSHIP,
    $6 AS SEGMENT,
    $7::DATE AS EFFECTIVE_DATE,
    '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM @CUSTOMER_STAGE/customer_updates.csv
WHERE $1 = 101;

SELECT * FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    $1 AS CUSTOMER_ID,
    $2 AS CUSTOMER_NAME,
    $3 AS CITY,
    $4 AS STATE,
    $5 AS CURRENT_MEMBERSHIP,
    'Silver' AS PREVIOUS_MEMBERSHIP,
    $5 AS HISTORICAL_MEMBERSHIP,
    $6 AS SEGMENT,
    $7::DATE AS EFFECTIVE_DATE,
    '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM @CUSTOMER_STAGE/customer_updates.csv
WHERE $1 = 103;

UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    $1 AS CUSTOMER_ID,
    $2 AS CUSTOMER_NAME,
    $3 AS CITY,
    $4 AS STATE,
    $5 AS CURRENT_MEMBERSHIP,
    'Gold' AS PREVIOUS_MEMBERSHIP,
    $5 AS HISTORICAL_MEMBERSHIP,
    $6 AS SEGMENT,
    $7::DATE AS EFFECTIVE_DATE,
    '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM @CUSTOMER_STAGE/customer_updates.csv
WHERE $1 = 104;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_RECORDS
FROM DIM_CUSTOMER_TYPE6;

SELECT * FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT * FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

SELECT * FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101 AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT COUNT(*) AS SCD_TYPE_3_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE3;

SELECT COUNT(*) AS SCD_TYPE_6_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6;

SELECT COUNT(*) AS SCD_TYPE_6_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE;

SELECT COUNT(*) AS SCD_TYPE_6_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE;