CREATE OR REPLACE SCHEMA RETAIL_P6;
USE SCHEMA RETAIL_P6;

CREATE OR REPLACE TABLE RETAIL_DB_P4.RETAIL_P6.DIM_CUSTOMER
    LIKE RETAIL_DB_P4.RETAIL.DIM_CUSTOMER;

INSERT INTO RETAIL_DB_P4.RETAIL_P6.DIM_CUSTOMER
    SELECT * FROM RETAIL_DB_P4.RETAIL.DIM_CUSTOMER;

CREATE OR REPLACE TABLE RETAIL_DB_P4.RETAIL_P6.DIM_PRODUCT
    LIKE RETAIL_DB_P4.RETAIL.DIM_PRODUCT;

INSERT INTO RETAIL_DB_P4.RETAIL_P6.DIM_PRODUCT
    SELECT * FROM RETAIL_DB_P4.RETAIL.DIM_PRODUCT;

CREATE OR REPLACE TABLE RETAIL_DB_P4.RETAIL_P6.DIM_BRANCH
    LIKE RETAIL_DB_P4.RETAIL.DIM_BRANCH;

INSERT INTO RETAIL_DB_P4.RETAIL_P6.DIM_BRANCH
    SELECT * FROM RETAIL_DB_P4.RETAIL.DIM_BRANCH;

CREATE OR REPLACE TABLE RETAIL_DB_P4.RETAIL_P6.DIM_DATE
    LIKE RETAIL_DB_P4.RETAIL.DIM_DATE;

INSERT INTO RETAIL_DB_P4.RETAIL_P6.DIM_DATE
    SELECT * FROM RETAIL_DB_P4.RETAIL.DIM_DATE;

CREATE OR REPLACE TABLE RETAIL_DB_P4.RETAIL_P6.FACT_SALES
    LIKE RETAIL_DB_P4.RETAIL.FACT_SALES;

INSERT INTO RETAIL_DB_P4.RETAIL_P6.FACT_SALES
    SELECT * FROM RETAIL_DB_P4.RETAIL.FACT_SALES;

SHOW TABLES;

USE DATABASE RETAIL_DB_P4;
USE SCHEMA RETAIL_P6;

CREATE OR REPLACE TABLE DIM_REGION (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_STATE (
    STATE_ID NUMBER PRIMARY KEY,
    STATE_NAME VARCHAR(50),
    REGION_ID NUMBER,

    FOREIGN KEY(REGION_ID) REFERENCES DIM_REGION(REGION_ID)
);

CREATE OR REPLACE TABLE DIM_CITY (
    CITY_ID NUMBER PRIMARY KEY,
    CITY_NAME VARCHAR(50),
    STATE_ID NUMBER,

    FOREIGN KEY(STATE_ID) REFERENCES DIM_STATE(STATE_ID)
);

INSERT INTO DIM_REGION (REGION_ID,REGION_NAME)
    SELECT 
        ROW_NUMBER() OVER (ORDER BY REGION_NAME) AS REGION_ID,
        REGION_NAME
    FROM (
        SELECT DISTINCT REGION AS REGION_NAME FROM DIM_BRANCH 
            WHERE REGION IS NOT NULL
);

SELECT * FROM DIM_REGION;

INSERT INTO DIM_STATE
    (STATE_ID, STATE_NAME, REGION_ID)
SELECT
    ROW_NUMBER() OVER (ORDER BY STATE_NAME) AS STATE_ID,
    STATE_NAME,
    REGION_ID
FROM (
    SELECT DISTINCT
        B.STATE AS STATE_NAME,
        R.REGION_ID
    FROM RETAIL_DB_P4.RETAIL.DIM_BRANCH B
    JOIN DIM_REGION R
        ON B.REGION = R.REGION_NAME
    WHERE B.STATE IS NOT NULL

    UNION

    SELECT 'Andhra Pradesh', 3
    UNION
    SELECT 'Bihar', 1
    UNION
    SELECT 'Chandigarh', 2
    UNION
    SELECT 'Madhya Pradesh', 2
);

SELECT * FROM DIM_STATE;

INSERT INTO DIM_CITY
    (CITY_ID, CITY_NAME, STATE_ID)
SELECT
    ROW_NUMBER() OVER (
        ORDER BY G.STATE_NAME, G.CITY_NAME
    ) AS CITY_ID,
    G.CITY_NAME,
    S.STATE_ID
FROM (
    SELECT DISTINCT
        CITY AS CITY_NAME,
        STATE AS STATE_NAME
    FROM RETAIL_DB_P4.RETAIL.DIM_BRANCH
    WHERE CITY IS NOT NULL
      AND STATE IS NOT NULL

    UNION

    SELECT DISTINCT
        CITY AS CITY_NAME,
        STATE AS STATE_NAME
    FROM RETAIL_DB_P4.RETAIL.DIM_CUSTOMER
    WHERE CITY IS NOT NULL
      AND STATE IS NOT NULL
) G
JOIN DIM_STATE S
    ON G.STATE_NAME = S.STATE_NAME;

SELECT * FROM DIM_CITY;


CREATE OR REPLACE TABLE DIM_CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_BRAND (
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR(50),
    CATEGORY_ID NUMBER,

    FOREIGN KEY(CATEGORY_ID) REFERENCES DIM_CATEGORY(CATEGORY_ID)
);

INSERT INTO DIM_CATEGORY (CATEGORY_ID,CATEGORY_NAME)
    SELECT
        DENSE_RANK() OVER (ORDER BY CATEGORY_NAME) AS CATEGORY_ID,
        CATEGORY_NAME
    FROM (
        SELECT DISTINCT CATEGORY AS CATEGORY_NAME
        FROM DIM_PRODUCT WHERE CATEGORY IS NOT NULL
);

SELECT * FROM DIM_CATEGORY;

INSERT INTO DIM_BRAND (BRAND_ID,BRAND_NAME,CATEGORY_ID)
    SELECT 
        ROW_NUMBER() OVER (ORDER BY P.BRAND_NAME,P.CATEGORY) AS BRAND_ID,
        P.BRAND_NAME,
        C.CATEGORY_ID
    FROM (
        SELECT DISTINCT BRAND AS BRAND_NAME,CATEGORY FROM DIM_PRODUCT
        WHERE BRAND IS NOT NULL AND CATEGORY IS NOT NULL
    ) AS P
    JOIN DIM_CATEGORY AS C
    ON C.CATEGORY_NAME=P.CATEGORY
;

SELECT * FROM DIM_BRAND;

CREATE OR REPLACE TABLE DIM_YEAR (
    YEAR_ID NUMBER PRIMARY KEY,
    YEAR NUMBER
);

INSERT INTO DIM_YEAR (YEAR_ID,YEAR)
    SELECT
        ROW_NUMBER() OVER (ORDER BY YEAR) AS YEAR_ID,
        YEAR
    FROM (
        SELECT DISTINCT YEAR FROM DIM_DATE WHERE YEAR IS NOT NULL
    )
;

SELECT * FROM DIM_YEAR;

CREATE OR REPLACE TABLE DIM_QUARTER (
    QUARTER_ID NUMBER PRIMARY KEY,
    QUARTER VARCHAR(10),
    YEAR_ID NUMBER,

    FOREIGN KEY(YEAR_ID) REFERENCES DIM_YEAR(YEAR_ID)
);

INSERT INTO DIM_QUARTER (QUARTER_ID,QUARTER,YEAR_ID)
    SELECT
        ROW_NUMBER() OVER (ORDER BY D.QUARTER) AS QUARTER_ID,
        D.QUARTER,
        Y.YEAR_ID
    FROM (
        SELECT DISTINCT QUARTER,YEAR FROM DIM_DATE
        WHERE QUARTER IS NOT NULL AND YEAR IS NOT NULL
    ) AS D
    JOIN DIM_YEAR AS Y
    ON D.YEAR=Y.YEAR
;

SELECT * FROM DIM_QUARTER;

CREATE OR REPLACE TABLE DIM_MONTH (
    MONTH_ID NUMBER PRIMARY KEY,
    MONTH VARCHAR(30),
    QUARTER_ID NUMBER,
    
    FOREIGN KEY (QUARTER_ID) REFERENCES DIM_QUARTER(QUARTER_ID)
);

INSERT INTO DIM_MONTH (MONTH_ID,MONTH,QUARTER_ID)
    SELECT 
        ROW_NUMBER() OVER (ORDER BY D.YEAR, D.QUARTER, D.MONTH) AS MONTH_ID,
        D.MONTH,
        Q.QUARTER_ID
    FROM (
        SELECT DISTINCT MONTH,QUARTER,YEAR FROM DIM_DATE
        WHERE MONTH IS NOT NULL
            AND QUARTER IS NOT NULL
            AND YEAR IS NOT NULL
    ) AS D
    JOIN DIM_YEAR AS Y
        ON Y.YEAR=D.YEAR
    JOIN DIM_QUARTER AS Q
        ON D.QUARTER=Q.QUARTER
        AND Q.YEAR_ID=Y.YEAR_ID
;    

SELECT * FROM DIM_MONTH;

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50),
    BRAND_ID NUMBER,
    PRICE NUMBER,

    FOREIGN KEY(BRAND_ID) REFERENCES DIM_BRAND(BRAND_ID)
);

INSERT INTO DIM_PRODUCT
    (PRODUCT_ID, PRODUCT_NAME, BRAND_ID, PRICE)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_ID,
    P.PRICE
FROM RETAIL_DB_P4.RETAIL.DIM_PRODUCT AS P
JOIN RETAIL_DB_P4.RETAIL_P6.DIM_CATEGORY AS C
    ON P.CATEGORY = C.CATEGORY_NAME
JOIN RETAIL_DB_P4.RETAIL_P6.DIM_BRAND AS B
    ON P.BRAND = B.BRAND_NAME
   AND C.CATEGORY_ID = B.CATEGORY_ID
;

SELECT * FROM DIM_PRODUCT;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(30),
    WEEK_NO NUMBER,
    MONTH_ID NUMBER,
    IS_WEEKEND BOOLEAN,
    FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH(MONTH_ID)
);

INSERT INTO DIM_DATE (DATE_ID,DATE,DAY,DAY_NAME,WEEK_NO,MONTH_ID,IS_WEEKEND)
SELECT
    D.DATE_ID,D.DATE,D.DAY,D.DAY_NAME,D.WEEK_NO,M.MONTH_ID,D.IS_WEEKEND
FROM RETAIL_DB_P4.RETAIL.DIM_DATE AS D
JOIN DIM_YEAR AS Y
    ON D.YEAR=Y.YEAR
JOIN DIM_QUARTER AS Q
    ON Q.QUARTER=D.QUARTER
    AND Q.YEAR_ID=Y.YEAR_ID
JOIN DIM_MONTH AS M
    ON M.MONTH=D.MONTH
    AND M.QUARTER_ID=Q.QUARTER_ID
;

SELECT * FROM DIM_DATE;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50),
    CITY_ID NUMBER,
    MEMBERSHIP VARCHAR(10),

    FOREIGN KEY(CITY_ID) REFERENCES DIM_CITY(CITY_ID)
);

INSERT INTO DIM_CUSTOMER
(CUSTOMER_ID,CUSTOMER_NAME,CITY_ID,MEMBERSHIP)
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,CI.CITY_ID,C.MEMBERSHIP
FROM RETAIL_DB_P4.RETAIL.DIM_CUSTOMER AS C
JOIN DIM_STATE AS S
    ON S.STATE_NAME=C.STATE
JOIN DIM_CITY AS CI
    ON CI.CITY_NAME=C.CITY
    AND CI.STATE_ID=S.STATE_ID
;

SELECT * FROM DIM_CUSTOMER;

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR(30),
    CITY_ID NUMBER,
    MANAGER_NAME VARCHAR(50),

    FOREIGN KEY (CITY_ID) REFERENCES DIM_CITY(CITY_ID)
);

INSERT INTO DIM_BRANCH (BRANCH_ID,BRANCH_NAME,CITY_ID,MANAGER_NAME)
SELECT 
    B.BRANCH_ID,
    B.BRANCH_NAME,
    C.CITY_ID,
    B.MANAGER_NAME
FROM RETAIL_DB_P4.RETAIL.DIM_BRANCH AS B 
JOIN DIM_REGION AS R 
    ON B.REGION=R.REGION_NAME
JOIN DIM_STATE AS S 
    ON B.STATE=S.STATE_NAME
    AND R.REGION_ID=S.REGION_ID
JOIN DIM_CITY AS C
    ON B.CITY=C.CITY_NAME
    AND S.STATE_ID=C.STATE_ID
;

SELECT * FROM DIM_BRANCH;

---Full geography drill-down
SELECT
    R.REGION_NAME,
    S.STATE_NAME,
    C.CITY_NAME,
    COUNT(DISTINCT B.BRANCH_ID) AS BRANCH_COUNT,
    COUNT(DISTINCT CU.CUSTOMER_ID) AS CUSTOMER_COUNT
FROM DIM_REGION R
JOIN DIM_STATE S
    ON R.REGION_ID = S.REGION_ID
JOIN DIM_CITY C
    ON S.STATE_ID = C.STATE_ID
LEFT JOIN DIM_BRANCH B
    ON C.CITY_ID = B.CITY_ID
LEFT JOIN DIM_CUSTOMER CU
    ON C.CITY_ID = CU.CITY_ID
GROUP BY
    R.REGION_NAME,
    S.STATE_NAME,
    C.CITY_NAME
ORDER BY
    R.REGION_NAME,
    S.STATE_NAME,
    C.CITY_NAME;

--Product hierarchy
SELECT
    C.CATEGORY_NAME,
    B.BRAND_NAME,
    COUNT(P.PRODUCT_ID) AS PRODUCT_COUNT
FROM DIM_CATEGORY C
JOIN DIM_BRAND B
    ON C.CATEGORY_ID = B.CATEGORY_ID
JOIN DIM_PRODUCT P
    ON B.BRAND_ID = P.BRAND_ID
GROUP BY
    C.CATEGORY_NAME,
    B.BRAND_NAME
ORDER BY
    C.CATEGORY_NAME,
    B.BRAND_NAME;

--Date hierarchy
SELECT
    Y.YEAR,
    Q.QUARTER,
    M.MONTH,
    COUNT(D.DATE_ID) AS DATE_COUNT
FROM DIM_YEAR Y
JOIN DIM_QUARTER Q
    ON Y.YEAR_ID = Q.YEAR_ID
JOIN DIM_MONTH M
    ON Q.QUARTER_ID = M.QUARTER_ID
JOIN DIM_DATE D
    ON M.MONTH_ID = D.MONTH_ID
GROUP BY
    Y.YEAR,
    Q.QUARTER,
    M.MONTH
ORDER BY
    Y.YEAR,
    Q.QUARTER,
    M.MONTH;

--Customer-wise Sales Report
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CI.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME,
    SUM(F.TOTAL_AMOUNT) AS CUSTOMER_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_CITY CI
    ON C.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CI.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME
ORDER BY CUSTOMER_REVENUE DESC;

--Product-wise Revenue Report
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS PRODUCT_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY C
    ON B.CATEGORY_ID = C.CATEGORY_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME
ORDER BY PRODUCT_REVENUE DESC;

--Brand-wise Revenue Report
SELECT
    B.BRAND_NAME,
    SUM(F.TOTAL_AMOUNT) AS BRAND_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
GROUP BY B.BRAND_NAME
ORDER BY BRAND_REVENUE DESC;

--Category-wise Revenue Report
SELECT
    C.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS CATEGORY_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY C
    ON B.CATEGORY_ID = C.CATEGORY_ID
GROUP BY C.CATEGORY_NAME
ORDER BY CATEGORY_REVENUE DESC;

--City-wise Sales Report
SELECT
    CI.CITY_NAME,
    SUM(F.TOTAL_AMOUNT) AS CITY_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
GROUP BY CI.CITY_NAME
ORDER BY CITY_REVENUE DESC;

--State-wise Revenue Report
SELECT
    S.STATE_NAME,
    SUM(F.TOTAL_AMOUNT) AS STATE_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
GROUP BY S.STATE_NAME
ORDER BY STATE_REVENUE DESC;

--Region-wise Revenue Report
SELECT
    R.REGION_NAME,
    SUM(F.TOTAL_AMOUNT) AS REGION_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME
ORDER BY REGION_REVENUE DESC;

--Monthly Revenue Report
SELECT
    Y.YEAR,
    Q.QUARTER,
    M.MONTH,
    SUM(F.TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY
    Y.YEAR,
    Q.QUARTER,
    M.MONTH
ORDER BY
    Y.YEAR,
    Q.QUARTER,
    M.MONTH;

--Quarterly Revenue Report
SELECT
    Y.YEAR,
    Q.QUARTER,
    SUM(F.TOTAL_AMOUNT) AS QUARTERLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY
    Y.YEAR,
    Q.QUARTER
ORDER BY
    Y.YEAR,
    Q.QUARTER;

--Top 10 Customers
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS CUSTOMER_REVENUE,
    DENSE_RANK() OVER (
        ORDER BY SUM(F.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
QUALIFY CUSTOMER_RANK <= 10
ORDER BY CUSTOMER_RANK;

--Top 10 Products
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS PRODUCT_REVENUE,
    DENSE_RANK() OVER (
        ORDER BY SUM(F.TOTAL_AMOUNT) DESC
    ) AS PRODUCT_RANK
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
QUALIFY PRODUCT_RANK <= 10
ORDER BY PRODUCT_RANK;

--Top 10 Branches
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    CI.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME,
    SUM(F.TOTAL_AMOUNT) AS BRANCH_REVENUE,
    DENSE_RANK() OVER (
        ORDER BY SUM(F.TOTAL_AMOUNT) DESC
    ) AS BRANCH_RANK
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    CI.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME
QUALIFY BRANCH_RANK <= 10
ORDER BY BRANCH_RANK;

--Customer Purchase Trend
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    Y.YEAR,
    M.MONTH,
    COUNT(F.SALE_ID) AS PURCHASE_COUNT,
    SUM(F.TOTAL_AMOUNT) AS CUSTOMER_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    Y.YEAR,
    M.MONTH
ORDER BY
    C.CUSTOMER_ID,
    Y.YEAR,
    M.MONTH;


--Product Performance Dashboard
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME,
    SUM(F.QUANTITY) AS QUANTITY_SOLD,
    SUM(F.TOTAL_AMOUNT) AS PRODUCT_REVENUE,
    AVG(F.TOTAL_AMOUNT) AS AVG_SALE_VALUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY C
    ON B.CATEGORY_ID = C.CATEGORY_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME
ORDER BY
    PRODUCT_REVENUE DESC;

--Regional Sales Dashboard
SELECT
    R.REGION_NAME,
    SUM(F.QUANTITY) AS QUANTITY_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REGION_REVENUE,
    COUNT(DISTINCT F.SALE_ID) AS SALES_COUNT,
    COUNT(DISTINCT B.BRANCH_ID) AS ACTIVE_BRANCHES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME
ORDER BY REGION_REVENUE DESC;