CREATE OR REPLACE WAREHOUSE HEALTHCARE_WH WAREHOUSE_SIZE='X-SMALL', AUTO_SUSPEND=60, AUTO_RESUME=TRUE;

USE WAREHOUSE HEALTHCARE_WH;

CREATE OR REPLACE DATABASE HEALTHCARE_DB;

USE DATABASE HEALTHCARE_DB;

CREATE OR REPLACE SCHEMA HEALTHCARE_SCHEMA;

USE SCHEMA HEALTHCARE_SCHEMA;


-- 1. PATIENT DIMENSION
CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PATIENT_ID VARCHAR(20),
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);


-- 2. DOCTOR DIMENSION
CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DOCTOR_ID VARCHAR(20),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);


-- 3. HOSPITAL DIMENSION
CREATE OR REPLACE TABLE DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID VARCHAR(20),
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50)
);


-- 4. DEPARTMENT DIMENSION
CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DEPARTMENT_ID VARCHAR(20),
    DEPARTMENT_NAME VARCHAR(100)
);


-- 5. TREATMENT DIMENSION
CREATE OR REPLACE TABLE DIM_TREATMENT (
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID VARCHAR(20),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(100)
);



CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE HEALTHCARE_STAGE FILE_FORMAT = CSV_FORMAT;

SHOW FILE FORMATS;

SHOW STAGES;

LIST @HEALTHCARE_STAGE;

COPY INTO DIM_PATIENT
(
    PATIENT_ID,
    PATIENT_NAME,
    GENDER,
    CITY,
    STATE
)
FROM @HEALTHCARE_STAGE/patients.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM DIM_PATIENT ORDER BY PATIENT_KEY;

COPY INTO DIM_DOCTOR
(
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
)
FROM @HEALTHCARE_STAGE/doctors.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM DIM_DOCTOR ORDER BY DOCTOR_KEY;

COPY INTO DIM_HOSPITAL
(
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    REGION
)
FROM @HEALTHCARE_STAGE/hospitals.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM DIM_HOSPITAL ORDER BY HOSPITAL_KEY;

COPY INTO DIM_DEPARTMENT
(
    DEPARTMENT_ID,
    DEPARTMENT_NAME
)
FROM @HEALTHCARE_STAGE/departments.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM DIM_DEPARTMENT ORDER BY DEPARTMENT_KEY;

COPY INTO DIM_TREATMENT
(
    TREATMENT_ID,
    TREATMENT_NAME,
    TREATMENT_CATEGORY
)
FROM @HEALTHCARE_STAGE/treatments.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM DIM_TREATMENT ORDER BY TREATMENT_KEY;


CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER PRIMARY KEY,
    FULL_DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH NUMBER,
    MONTH_NAME VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER
);

INSERT INTO DIM_DATE
(
    DATE_KEY,
    FULL_DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR
)
SELECT
    TO_NUMBER(TO_CHAR(generated_date, 'YYYYMMDD')),
    DATE(generated_date),
    DAY(generated_date),
    DAYNAME(generated_date),
    WEEK(generated_date),
    MONTH(generated_date),
    MONTHNAME(generated_date),
    CONCAT('Q', QUARTER(generated_date)),
    YEAR(generated_date)
FROM (
    SELECT DATEADD(
        DAY,
        SEQ4(),
        '2026-01-01'
    ) AS generated_date
    FROM TABLE(GENERATOR(ROWCOUNT => 90))
);

SELECT COUNT(*) AS TOTAL_DATES FROM DIM_DATE;

SELECT
    MIN(FULL_DATE) AS START_DATE,
    MAX(FULL_DATE) AS END_DATE,
    COUNT(*) AS TOTAL_DATES
FROM DIM_DATE;


CREATE OR REPLACE TABLE FACT_ADMISSION (
    ADMISSION_KEY NUMBER AUTOINCREMENT(1,1) PRIMARY KEY,

    PATIENT_KEY NUMBER,
    DOCTOR_KEY NUMBER,
    HOSPITAL_KEY NUMBER,
    DEPARTMENT_KEY NUMBER,
    DATE_KEY NUMBER,

    ADMISSION_COUNT NUMBER,
    LENGTH_OF_STAY NUMBER,

    FOREIGN KEY (PATIENT_KEY)
        REFERENCES DIM_PATIENT(PATIENT_KEY),

    FOREIGN KEY (DOCTOR_KEY)
        REFERENCES DIM_DOCTOR(DOCTOR_KEY),

    FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),

    FOREIGN KEY (DEPARTMENT_KEY)
        REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),

    FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY)
);

INSERT INTO FACT_ADMISSION
(
    PATIENT_KEY,
    DOCTOR_KEY,
    HOSPITAL_KEY,
    DEPARTMENT_KEY,
    DATE_KEY,
    ADMISSION_COUNT,
    LENGTH_OF_STAY
)
SELECT
    pat.PATIENT_KEY,
    doc.DOCTOR_KEY,
    hos.HOSPITAL_KEY,
    dep.DEPARTMENT_KEY,
    dat.DATE_KEY,
    1 AS ADMISSION_COUNT,
    DATEDIFF(
        DAY,
        adm_file.$6::DATE,
        adm_file.$7::DATE
    ) AS LENGTH_OF_STAY
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7
    FROM @HEALTHCARE_STAGE/admissions.csv
) AS adm_file
INNER JOIN DIM_PATIENT pat
    ON adm_file.$2 = pat.PATIENT_ID
INNER JOIN DIM_DOCTOR doc
    ON adm_file.$3 = doc.DOCTOR_ID
INNER JOIN DIM_HOSPITAL hos
    ON adm_file.$4 = hos.HOSPITAL_ID
INNER JOIN DIM_DEPARTMENT dep
    ON adm_file.$5 = dep.DEPARTMENT_ID
INNER JOIN DIM_DATE dat
    ON adm_file.$6::DATE = dat.FULL_DATE;

SELECT COUNT(*) AS TOTAL_ROWS FROM FACT_ADMISSION;

CREATE OR REPLACE TABLE FACT_BILLING (
    BILLING_KEY NUMBER AUTOINCREMENT(1,1) PRIMARY KEY,

    PATIENT_KEY NUMBER,
    DOCTOR_KEY NUMBER,
    HOSPITAL_KEY NUMBER,
    DEPARTMENT_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    DATE_KEY NUMBER,

    QUANTITY NUMBER,
    TREATMENT_AMOUNT NUMBER(12,2),
    DISCOUNT NUMBER(12,2),
    NET_AMOUNT NUMBER(12,2),

    FOREIGN KEY (PATIENT_KEY)
        REFERENCES DIM_PATIENT(PATIENT_KEY),

    FOREIGN KEY (DOCTOR_KEY)
        REFERENCES DIM_DOCTOR(DOCTOR_KEY),

    FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),

    FOREIGN KEY (DEPARTMENT_KEY)
        REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),

    FOREIGN KEY (TREATMENT_KEY)
        REFERENCES DIM_TREATMENT(TREATMENT_KEY),

    FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY)
);

INSERT INTO FACT_BILLING
(
    PATIENT_KEY,
    DOCTOR_KEY,
    HOSPITAL_KEY,
    DEPARTMENT_KEY,
    TREATMENT_KEY,
    DATE_KEY,
    QUANTITY,
    TREATMENT_AMOUNT,
    DISCOUNT,
    NET_AMOUNT
)
SELECT
    pat.PATIENT_KEY,
    doc.DOCTOR_KEY,
    hos.HOSPITAL_KEY,
    dep.DEPARTMENT_KEY,
    trt.TREATMENT_KEY,
    dat.DATE_KEY,
    bill_file.$8::NUMBER,
    bill_file.$9::NUMBER,
    bill_file.$10::NUMBER,
    bill_file.$9::NUMBER - bill_file.$10::NUMBER
FROM (
    SELECT
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10
    FROM @HEALTHCARE_STAGE/billing.csv
) AS bill_file
INNER JOIN DIM_PATIENT pat
    ON bill_file.$2 = pat.PATIENT_ID
INNER JOIN DIM_DOCTOR doc
    ON bill_file.$3 = doc.DOCTOR_ID
INNER JOIN DIM_HOSPITAL hos
    ON bill_file.$4 = hos.HOSPITAL_ID
INNER JOIN DIM_DEPARTMENT dep
    ON bill_file.$5 = dep.DEPARTMENT_ID
INNER JOIN DIM_TREATMENT trt
    ON bill_file.$6 = trt.TREATMENT_ID
INNER JOIN DIM_DATE dat
    ON bill_file.$7::DATE = dat.FULL_DATE;



SELECT
    h.HOSPITAL_NAME,
    SUM(f.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION f
INNER JOIN DIM_HOSPITAL h
    ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
GROUP BY h.HOSPITAL_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

--Hospital-wise Revenue
SELECT
    h.HOSPITAL_NAME,
    SUM(f.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING f
INNER JOIN DIM_HOSPITAL h
    ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
GROUP BY h.HOSPITAL_NAME
ORDER BY TOTAL_REVENUE DESC;

--Monthly Revenue
SELECT
    TO_CHAR(d.FULL_DATE, 'YYYY-MM') AS MONTH,
    SUM(f.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING f
INNER JOIN DIM_DATE d
    ON f.DATE_KEY = d.DATE_KEY
GROUP BY TO_CHAR(d.FULL_DATE, 'YYYY-MM')
ORDER BY MONTH;

--Doctor-wise Revenue
SELECT
    d.DOCTOR_NAME AS DOCTOR,
    SUM(f.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING f
INNER JOIN DIM_DOCTOR d
    ON f.DOCTOR_KEY = d.DOCTOR_KEY
GROUP BY d.DOCTOR_NAME
ORDER BY TOTAL_REVENUE DESC;

--Drill-Across Analysis
SELECT
    h.HOSPITAL_NAME,
    COALESCE(a.TOTAL_ADMISSIONS, 0) AS TOTAL_ADMISSIONS,
    COALESCE(b.TOTAL_REVENUE, 0) AS TOTAL_REVENUE
FROM DIM_HOSPITAL h

LEFT JOIN (
    SELECT
        HOSPITAL_KEY,
        SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS
    FROM FACT_ADMISSION
    GROUP BY HOSPITAL_KEY
) a
    ON h.HOSPITAL_KEY = a.HOSPITAL_KEY

LEFT JOIN (
    SELECT
        HOSPITAL_KEY,
        SUM(NET_AMOUNT) AS TOTAL_REVENUE
    FROM FACT_BILLING
    GROUP BY HOSPITAL_KEY
) b
    ON h.HOSPITAL_KEY = b.HOSPITAL_KEY

ORDER BY TOTAL_ADMISSIONS DESC;