CREATE OR REPLACE DATABASE PROJECT_9_DB;

CREATE OR REPLACE SCHEMA PROJECT_9_DB.CUSTOMER_HISTORY;

-- Set the database and schema as the current working context
USE DATABASE PROJECT_9_DB;

USE SCHEMA CUSTOMER_HISTORY;


CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1;

CREATE OR REPLACE STAGE CUSTOMER_STAGE FILE_FORMAT = CUSTOMER_CSV_FORMAT;

SHOW STAGES;

LIST @CUSTOMER_STAGE;

-- TASK 2: CREATE SCD TYPE 1 TABLE

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1
(
    CUSTOMER_KEY  NUMBER AUTOINCREMENT,
    CUSTOMER_ID   NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY          VARCHAR(50),
    STATE         VARCHAR(50),
    MEMBERSHIP    VARCHAR(30),
    SEGMENT       VARCHAR(30)
);

DESC TABLE DIM_CUSTOMER_TYPE1;

LIST @CUSTOMER_STAGE;

COPY INTO DIM_CUSTOMER_TYPE1
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM
(
    SELECT $1,$2,$3,$4,$5,$6 FROM @CUSTOMER_STAGE/customers_initial.csv
)
FILE_FORMAT = (
    FORMAT_NAME = 'CUSTOMER_CSV_FORMAT'
);

SELECT * FROM DIM_CUSTOMER_TYPE1;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID    NUMBER,
    CUSTOMER_NAME  VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    MEMBERSHIP     VARCHAR(30),
    SEGMENT        VARCHAR(30),
    EFFECTIVE_DATE DATE
);

LIST @CUSTOMER_STAGE;

COPY INTO CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE
)
FROM
(
    SELECT
        $1::NUMBER,
        $2::VARCHAR(100),
        $3::VARCHAR(50),
        $4::VARCHAR(50),
        $5::VARCHAR(30),
        $6::VARCHAR(30),
        $7::DATE
    FROM @CUSTOMER_STAGE/customer_updates.csv
)
FILE_FORMAT = (
    FORMAT_NAME = 'CUSTOMER_CSV_FORMAT'
);

SELECT * FROM CUSTOMER_UPDATES;

UPDATE DIM_CUSTOMER_TYPE1 AS TARGET
SET
    CUSTOMER_NAME = SOURCE.CUSTOMER_NAME,
    CITY          = SOURCE.CITY,
    STATE         = SOURCE.STATE,
    MEMBERSHIP    = SOURCE.MEMBERSHIP,
    SEGMENT       = SOURCE.SEGMENT
FROM CUSTOMER_UPDATES AS SOURCE
WHERE TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID;

SELECT * FROM DIM_CUSTOMER_TYPE1 ORDER BY CUSTOMER_ID;

SELECT COUNT(*) AS TOTAL_RECORDS FROM DIM_CUSTOMER_TYPE1;

SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101;

-- TASK 7: CREATE SCD TYPE 2 TABLE

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2
(
    CUSTOMER_KEY   NUMBER AUTOINCREMENT,
    CUSTOMER_ID    NUMBER,
    CUSTOMER_NAME  VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    MEMBERSHIP     VARCHAR(30),
    SEGMENT        VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE    DATE,
    IS_CURRENT     BOOLEAN
);

DESC TABLE DIM_CUSTOMER_TYPE2;

INSERT INTO DIM_CUSTOMER_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    $1::NUMBER,
    $2::VARCHAR(100),
    $3::VARCHAR(50),
    $4::VARCHAR(50),
    $5::VARCHAR(30),
    $6::VARCHAR(30),
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM @CUSTOMER_STAGE/customers_initial.csv
(
    FILE_FORMAT => 'CUSTOMER_CSV_FORMAT'
);

SELECT * FROM DIM_CUSTOMER_TYPE2;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE2;

UPDATE DIM_CUSTOMER_TYPE2 AS TARGET
SET
    EXPIRY_DATE = DATEADD(DAY, -1, SOURCE.EFFECTIVE_DATE),
    IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES AS SOURCE
WHERE TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
  AND TARGET.IS_CURRENT = TRUE;

SELECT * FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID IN (101, 103, 104)
ORDER BY CUSTOMER_ID;

INSERT INTO DIM_CUSTOMER_TYPE2
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES;

SELECT * FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

--Customer 101 Type 2 Change
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

--Customer 103 Type 2 Change
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;

--Customer 104 Type 2 Change
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;

--Display Complete SCD Type 2 History
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

--Display Current Customer Records
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

--Historical Customer Analysis
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT COUNT(*) AS SCD_TYPE_1_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE1;

SELECT COUNT(*) AS SCD_TYPE_2_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2;

SELECT COUNT(*) AS SCD_TYPE_2_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE;

SELECT COUNT(*) AS SCD_TYPE_2_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = FALSE;