-- TASK 1: CREATE DATABASE AND SCHEMA

CREATE OR REPLACE DATABASE PROJECT_8;

CREATE OR REPLACE SCHEMA PROJECT_8.SCD_SCHEMA;

-- Use the database and schema
USE DATABASE PROJECT_8;
USE SCHEMA SCD_SCHEMA;

-- TASK 2: CREATE INITIAL CUSTOMER DIMENSION

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

DESC TABLE DIM_CUSTOMER;

-- TASK 3: CREATE STAGE

CREATE OR REPLACE STAGE CUSTOMER_STAGE;

SHOW STAGES;

LIST @CUSTOMER_STAGE;

COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

-- TASK 4: DISPLAY INITIAL CUSTOMER DIMENSION

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

-- TASK 5: CREATE CUSTOMER UPDATES TABLE

CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

CREATE OR REPLACE STAGE CUSTOMER_UPDATE_STAGE;

SHOW STAGES;

LIST @CUSTOMER_UPDATE_STAGE;

COPY INTO CUSTOMER_UPDATES
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_UPDATE_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

SELECT * FROM CUSTOMER_UPDATES ORDER BY CUSTOMER_ID;

-- TASK 6: IDENTIFY CHANGED CUSTOMERS

SELECT
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER d
INNER JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE
       d.CITY <> u.CITY
    OR d.STATE <> u.STATE
    OR d.MEMBERSHIP <> u.MEMBERSHIP
    OR d.SEGMENT <> u.SEGMENT
ORDER BY d.CUSTOMER_ID;

-- TASK 7: IDENTIFY ATTRIBUTE CHANGES

SELECT
    d.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    d.CITY AS OLD_VALUE,
    u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    d.STATE AS OLD_VALUE,
    u.STATE AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.STATE <> u.STATE

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    d.MEMBERSHIP AS OLD_VALUE,
    u.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.MEMBERSHIP <> u.MEMBERSHIP

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    d.SEGMENT AS OLD_VALUE,
    u.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.SEGMENT <> u.SEGMENT

ORDER BY CUSTOMER_ID, ATTRIBUTE;