CREATE WAREHOUSE RETAIL_DW_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 60;

USE WAREHOUSE RETAIL_DW_WH;

CREATE DATABASE RETAIL_DW;

CREATE SCHEMA RETAIL_DW.SALES_ANALYTICS;

USE DATABASE RETAIL_DW;

USE SCHEMA SALES_ANALYTICS;

CREATE OR REPLACE TABLE DIM_STORE
(
    STORE_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID       NUMBER,
    STORE_NAME     VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    STORE_MANAGER  VARCHAR(100)
);

DESC TABLE DIM_STORE;

CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID   NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY     VARCHAR(50),
    UNIT_PRICE   NUMBER(10,2)
);

DESC TABLE DIM_PRODUCT;

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID
(
    CUSTOMER_KEY          NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID           NUMBER,
    CUSTOMER_NAME         VARCHAR(100),

    CITY                  VARCHAR(50),
    PREVIOUS_CITY         VARCHAR(50),
    STATE                 VARCHAR(50),

    CURRENT_MEMBERSHIP    VARCHAR(30),
    PREVIOUS_MEMBERSHIP   VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),

    SEGMENT               VARCHAR(30),

    EFFECTIVE_DATE        DATE,
    EXPIRY_DATE           DATE,
    IS_CURRENT            BOOLEAN
);

DESC TABLE DIM_CUSTOMER_HYBRID;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RAW_STAGE FILE_FORMAT = CSV_FORMAT;

LIST @RAW_STAGE;

COPY INTO DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
)
FROM (
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5
    FROM @RAW_STAGE/stores.csv
);

COPY INTO DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE
)
FROM (
    SELECT
        $1,
        $2,
        $3,
        $4
    FROM @RAW_STAGE/products.csv
);

COPY INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        NULL,
        $4,
        $5,
        NULL,
        $5,
        $6,
        '2026-01-01',
        '9999-12-31',
        TRUE
    FROM @RAW_STAGE/customers_initial.csv
);

SELECT * FROM DIM_CUSTOMER_HYBRID ORDER BY CUSTOMER_ID;

CREATE OR REPLACE TABLE FACT_SALES
(
    SALES_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID   VARCHAR(50),
    TRANSACTION_DATE DATE,

    CUSTOMER_KEY     NUMBER,
    STORE_KEY        NUMBER,
    PRODUCT_KEY      NUMBER,

    QUANTITY         NUMBER,
    UNIT_PRICE       NUMBER(10,2),
    TOTAL_AMOUNT     NUMBER(12,2),

    FOREIGN KEY (CUSTOMER_KEY)
        REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),

    FOREIGN KEY (STORE_KEY)
        REFERENCES DIM_STORE(STORE_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES DIM_PRODUCT(PRODUCT_KEY)
);

DESC TABLE FACT_SALES;

INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1001',
    '2026-02-15',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    1,
    P.UNIT_PRICE,
    1 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C
JOIN DIM_STORE S
    ON S.STORE_ID = 201
JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 501
WHERE C.CUSTOMER_ID = 101
  AND C.IS_CURRENT = TRUE;

  INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-1002',
    '2026-03-10',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    2,
    P.UNIT_PRICE,
    2 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C
JOIN DIM_STORE S
    ON S.STORE_ID = 203
JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 502
WHERE C.CUSTOMER_ID = 103
  AND C.IS_CURRENT = TRUE;

SELECT
    SALES_KEY,
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
FROM FACT_SALES
ORDER BY SALES_KEY;

SELECT
    F.TRANSACTION_ID,
    F.TRANSACTION_DATE,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    S.STORE_ID,
    S.STORE_NAME,
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    F.QUANTITY,
    F.UNIT_PRICE,
    F.TOTAL_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER_HYBRID C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
JOIN DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY
JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
ORDER BY F.TRANSACTION_DATE;

SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;

UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;

SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;

UPDATE DIM_CUSTOMER_HYBRID HYB
SET
    EXPIRY_DATE = DATEADD(DAY, -1, TO_DATE(UPD.$7)),
    IS_CURRENT = FALSE
FROM @RAW_STAGE/customer_updates.csv AS UPD
WHERE HYB.CUSTOMER_ID = UPD.$1
  AND HYB.IS_CURRENT = TRUE;

  SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CITY,
    CURRENT_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID IN (101,103,104)
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

INSERT INTO DIM_CUSTOMER_HYBRID
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    UPD.$1,
    UPD.$2,
    UPD.$3,
    HYB.CITY,
    UPD.$4,
    UPD.$5,
    HYB.CURRENT_MEMBERSHIP,
    UPD.$5,
    UPD.$6,
    TO_DATE(UPD.$7),
    TO_DATE('9999-12-31'),
    TRUE
FROM @RAW_STAGE/customer_updates.csv AS UPD
JOIN DIM_CUSTOMER_HYBRID HYB
    ON UPD.$1 = HYB.CUSTOMER_ID
   AND HYB.IS_CURRENT = FALSE
   AND HYB.EXPIRY_DATE = DATEADD(DAY, -1, TO_DATE(UPD.$7));

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID IN (101,103,104)
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

UPDATE DIM_CUSTOMER_HYBRID HYB
SET
    CITY = HYB1.CITY,
    PREVIOUS_CITY = HYB1.PREVIOUS_CITY,
    STATE = HYB1.STATE,
    CURRENT_MEMBERSHIP = HYB1.CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = HYB1.PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_HYBRID HYB1
WHERE HYB1.IS_CURRENT = TRUE
  AND HYB.CUSTOMER_ID = HYB1.CUSTOMER_ID
  AND HYB.IS_CURRENT = FALSE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID IN (101,103,104)
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CITY,
    CURRENT_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

INSERT INTO FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT
    'TXN-2001',
    '2026-04-15',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    1,
    P.UNIT_PRICE,
    1 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C
JOIN DIM_STORE S
    ON S.STORE_ID = 201
JOIN DIM_PRODUCT P
    ON P.PRODUCT_ID = 503
WHERE C.CUSTOMER_ID = 101
  AND C.IS_CURRENT = TRUE;

  SELECT
    F.TRANSACTION_ID,
    F.TRANSACTION_DATE,
    F.CUSTOMER_KEY AS FACT_CUSTOMER_KEY,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.SEGMENT,
    C.HISTORICAL_MEMBERSHIP,
    C.IS_CURRENT,
    F.STORE_KEY,
    F.PRODUCT_KEY,
    F.QUANTITY,
    F.UNIT_PRICE,
    F.TOTAL_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER_HYBRID C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
WHERE F.TRANSACTION_ID = 'TXN-2001';

SELECT
    F.TRANSACTION_ID,
    F.TRANSACTION_DATE,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_KEY,
    C.HISTORICAL_MEMBERSHIP,
    C.SEGMENT,
    F.PRODUCT_KEY,
    F.TOTAL_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER_HYBRID C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
WHERE C.CUSTOMER_ID = 101
ORDER BY F.TRANSACTION_DATE;

SELECT * FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID,EFFECTIVE_DATE;

SELECT
    F.TRANSACTION_ID,
    F.TRANSACTION_DATE,
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY AS CURRENT_CITY,
    C.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
    C.SEGMENT AS SEGMENT_AT_PURCHASE,
    S.STORE_NAME,
    P.PRODUCT_NAME,
    F.TOTAL_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER_HYBRID C
    ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
JOIN DIM_STORE S
    ON F.STORE_KEY = S.STORE_KEY
JOIN DIM_PRODUCT P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
WHERE C.CUSTOMER_ID = 101
ORDER BY F.TRANSACTION_DATE;

SELECT
    'STORE DIMENSION RECORDS' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_STORE

UNION ALL

SELECT
    'PRODUCT DIMENSION RECORDS',
    COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT
    'TOTAL CUSTOMER DIMENSION RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT
    'CURRENT CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'HISTORICAL CUSTOMER RECORDS',
    COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE

UNION ALL

SELECT
    'FACT SALES TRANSACTIONS',
    COUNT(*)
FROM FACT_SALES;